version: "3"
services:
  node:
    image: "node:lts-alpine"
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"

  nginx:
    container_name: snapdrop
    image: "nginx:stable"
    restart: unless-stopped
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/ssl/certs
      - ./docker/openssl:/mnt/openssl
    ports:
      - "8080:80"
      - "443:443"
    env_file: ./docker/fqdn.env
    entrypoint: /mnt/openssl/create.sh
    command: ["nginx", "-g", "daemon off;"]